'use client';
import { useEditor } from './EditorContext';
export function useEditorActions() {
  const e = useEditor();
  return [
    {
      id: 'new-text',
      label: 'New text clip',
      group: 'Create',
      key: 'N',
      icon: 'plus',
      run: e.addClip,
    },
    {
      id: 'new-shape',
      label: 'New shape clip',
      group: 'Create',
      key: 'Shift N',
      icon: 'diamond',
      run: () => e.addVisual('shape'),
    },
    {
      id: 'new-image',
      label: 'Import image',
      group: 'Create',
      key: '',
      icon: 'film',
      run: () => e.imageInput.current?.click(),
    },
    {
      id: 'new-audio',
      label: 'Import audio',
      group: 'Create',
      key: '',
      icon: 'music',
      run: () => e.audioInput.current?.click(),
    },
    {
      id: 'new-project',
      label: 'New composition',
      group: 'Create',
      key: '⌘/Ctrl Alt N',
      icon: 'folder',
      run: e.newProject,
    },
    {
      id: 'duplicate',
      label: 'Duplicate selected clip',
      group: 'Edit',
      key: '⌘/Ctrl D',
      icon: 'duplicate',
      run: e.duplicateClip,
    },
    {
      id: 'delete',
      label: 'Delete selection',
      group: 'Edit',
      key: 'Delete',
      icon: 'trash',
      run: e.deleteSelection,
    },
    {
      id: 'trim-start',
      label: 'Trim start to playhead',
      group: 'Edit',
      key: 'Q',
      icon: 'trim',
      run: () => e.trimToPlayhead('start'),
    },
    {
      id: 'trim-end',
      label: 'Trim end to playhead',
      group: 'Edit',
      key: 'W',
      icon: 'trim',
      run: () => e.trimToPlayhead('end'),
    },
    {
      id: 'split',
      label: 'Split clip at playhead',
      group: 'Edit',
      key: 'S',
      icon: 'trim',
      run: e.splitClip,
    },
    {
      id: 'undo',
      label: 'Undo',
      group: 'Edit',
      key: '⌘/Ctrl Z',
      icon: 'undo',
      run: () => e.undo(),
      disabled: !e.historyCount.past,
    },
    {
      id: 'redo',
      label: 'Redo',
      group: 'Edit',
      key: '⌘/Ctrl Shift Z',
      icon: 'redo',
      run: () => e.undo(true),
      disabled: !e.historyCount.future,
    },
    {
      id: 'marker',
      label: 'Add timeline marker',
      group: 'Timeline',
      key: 'M',
      icon: 'marker',
      run: e.addMarker,
    },
    {
      id: 'prev-marker',
      label: 'Previous marker',
      group: 'Timeline',
      key: 'Alt M',
      icon: 'rewind',
      run: () => e.navigateMarker(-1),
    },
    {
      id: 'next-marker',
      label: 'Next marker',
      group: 'Timeline',
      key: 'Shift M',
      icon: 'arrow',
      run: () => e.navigateMarker(1),
    },
    {
      id: 'loop',
      label: 'Loop selected clip',
      group: 'Timeline',
      key: '',
      icon: 'loop',
      run: e.loopClip,
    },
    {
      id: 'fit',
      label: 'Fit timeline',
      group: 'Timeline',
      key: 'F',
      icon: 'frame',
      run: e.fitTimeline,
    },
    {
      id: 'code',
      label: 'Edit project code',
      group: 'Project',
      key: '',
      icon: 'code',
      run: () => e.openJSON(),
    },
    {
      id: 'export',
      label: 'Export composition',
      group: 'Project',
      key: '',
      icon: 'download',
      run: () => e.setModal('export'),
    },
    {
      id: 'save',
      label: 'Save project locally',
      group: 'Project',
      key: '⌘/Ctrl S',
      icon: 'save',
      run: e.saveProject,
    },
    {
      id: 'help',
      label: 'Keyboard shortcuts',
      group: 'Project',
      key: '?',
      icon: 'keyboard',
      run: () => e.setModal('help'),
    },
  ];
}
