import {
  Play,
  Pause,
  Plus,
  X,
  ChevronRight,
  ChevronDown,
  Undo2,
  Redo2,
  Layers,
  Sparkles,
  Download,
  Upload,
  Save,
  SlidersHorizontal,
  Eye,
  EyeOff,
  Code2,
  Music,
  Trash2,
  Copy,
  Search,
  ArrowRight,
  House,
  Maximize,
  Diamond,
  SkipBack,
  Repeat,
  Film,
  Check,
  Folder,
  Zap,
  CircleHelp,
  Scissors,
  Flag,
  Keyboard,
  PanelLeft,
  type LucideIcon,
} from 'lucide-react';
const icons: Record<string, LucideIcon> = {
  play: Play,
  pause: Pause,
  plus: Plus,
  close: X,
  chevron: ChevronRight,
  down: ChevronDown,
  undo: Undo2,
  redo: Redo2,
  layers: Layers,
  spark: Sparkles,
  download: Download,
  upload: Upload,
  save: Save,
  settings: SlidersHorizontal,
  eye: Eye,
  hidden: EyeOff,
  code: Code2,
  music: Music,
  trash: Trash2,
  duplicate: Copy,
  search: Search,
  arrow: ArrowRight,
  home: House,
  frame: Maximize,
  diamond: Diamond,
  rewind: SkipBack,
  loop: Repeat,
  film: Film,
  check: Check,
  folder: Folder,
  bolt: Zap,
  help: CircleHelp,
  trim: Scissors,
  marker: Flag,
  keyboard: Keyboard,
  panel: PanelLeft,
};
export default function Icon({
  name,
}: {
  name: string;
  size?: number;
  style?: React.CSSProperties;
}) {
  const Component = icons[name] || Sparkles;
  return <Component className="size-4 shrink-0" strokeWidth={1.75} aria-hidden />;
}
